### ISSUE TITLE
The Tail at Scale

### ISSUE THREAD

**Issue by h8k** [h8k/study#98]
https://www.dropbox.com/s/vd3divhvrkjqdv7/longtail.pdf?dl=0

**Comment by h8k** [comment]
안그래도 요새 P99는 10ms 미만인데 왜 자꾸 tail에 있는 애는 120ms 타임아웃이 나나 궁금했음

**Comment by zxzl** [comment]
https://blog.shik.kr/tail-at-scale/

**Comment by h8k** [comment]
https://blog.shik.kr/tail-at-scale/
